server:
  port: 8080

spring:
  application:
    name: gateway-service
  
  profiles:
    active: dev
    
  main:
    banner-mode: console
    
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false # Manual configuration for now
      
# Development profile
---
spring:
  config:
    activate:
      on-profile: dev
      
logging:
  level:
    com.quizplatform: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always